export const mathsTopics = [
   "FOM",
   "Quadratic Equations",
   "Trignometry",
   "Sequence n Series",
   "Determinant",
   "Straight Line",
   "Cicle",
   "Conic Section",
   "Vector",
   "3D",
   "Function",
   "ITF",
   "Limits",
   "Continuity differentiability",
   "MOD",
   "AOD",
   "Integration",
   "Differential Equations",
   "Probability",
   "Matrices"
]

export const physicsTopics = [
    "Basic Maths",
    "kinematics",
    "NLM",
    "WPE",
    "Circular Motion", 
    "Center of Mass",
    "Rotation",
    "SHM",
    "Waves",
    "KTG",
    "Thermodynamics",
    "Thermal Physics",
    "Solids",
    "Fluids",
    "Electrostatics",
    "Capacitors",
    "Current Electricity",
    "Magnetism",
    "MEC",
    "EMI",
    "Ray Optics",
    "Wave Optics",
    "Modern Physics",
]

export const chemistryTopics = [
    "Mole Concepts",
    "Chemical Equilibrium",
    "Chemical Kinetics",
    "Atomic Stucture",
    "Redox Reaction",
    "Thermodynamics",
    "Electrochemistry",
    "Ionic Equilibrium",
    "Liquid Soltion",
    "Solid State",
    "Surface Chemistry",
   "Periodic Table",
    "Chemical Bonding",
    "Coordination Compounds",
    "Mettulargy",
    "S-block",
    "P-block",
    "D&F-block",
    "Salt Analysis",
    "Environmental Chemistry",
    "IUPAC",
    "GOC",
    "Hydrocarbons",
    "Halides",
    "Grignard Reagents",
    "Alcohol Phenol Ether",
    "Carbonyl Compounds",
    "Carboxylic Acid",
    "Amines",
    "POC",
    "Polymers",
    "Biomolecules",
    "CIEL"


]

export const biologyTopics = [
   "The Living World",
   "Biological Classification",
   "Plant Kingdom",
    "Animal Kingdom",
    "Morphology of Flowering Plants",
    "Anatomy of Flowering Plants",
    "Structural Organisation In Animals",
    "CELLS",
    "Biomolecules",
    "Cell Cycle and Cell division",
    "Transport in Plants",
    "Mineral Nutrition",
    "Photosynthesis in higher plants",
    "Respiration in Plants",
    "Plant Growht and development",
    "breathing and exchange of gases",
    "Body fluids and circulation",
    "excretory products and their elimination",
    "locomotion and movement",
    "disorders",
    "chemical coordination",
    "sexual reproduction in plants",
    "human reproduction",
    "reproductive health",
    "principles of inheritance",
    "molecular basis of inheritance",
    "evolution",
    "human health and diseases",
    "microbes in human welfare",
    "biotechnology",
    "organisms and populations",
    "ecosystems",
    "biodiversity and conservation"

]