export const mathsTopics = [
   "FOM",
   "Quadratic Equations",
   "Trignometry",
   "Sequence n Series",
   "Determinant",
   "Straight Line",
   "Cicle",
   "Conic Section",
   "Vector",
   "3D",
   "Function",
   "ITF",
   "Limits",
   "Continuity differentiability",
   "MOD",
   "AOD",
   "Integration",
   "Differential Equations",
   "Probability",
   "Matrices"
]

export const physicsTopics = [
    "Basic Maths",
    "kinematics",
    "NLM",
    "WPE",
    "Circular Motion", 
    "Center of Mass",
    "Rotation",
    "SHM",
    "Waves",
    "KTG",
    "Thermodynamics",
    "Thermal Physics",
    "Solids",
    "Fluids",
    "Electrostatics",
    "Capacitors",
    "Current Electricity",
    "Magnetism",
    "MEC",
    "EMI",
    "Ray Optics",
    "Wave Optics",
    "Modern Physics",
]

export const chemistryTopics = [
    "Mole Concepts",
    "Chemical Equilibrium",
    "Chemical Kinetics",
    "Atomic Stucture",
    "Redox Reaction",
    "Thermodynamics",
    "Electrochemistry",
    "Ionic Equilibrium",
    "Liquid Soltion",
    "Solid State",
    "Surface Chemistry",
   "Periodic Table",
    "Chemical Bonding",
    "Coordination Compounds",
    "Mettulargy",
    "S-block",
    "P-block",
    "D&F-block",
    "Salt Analysis",
    "Environmental Chemistry",
    "IUPAC",
    "GOC",
    "Hydrocarbons",
    "Halides",
    "Grignard Reagents",
    "Alcohol Phenol Ether",
    "Carbonyl Compounds",
    "Carboxylic Acid",
    "Amines",
    "POC",
    "Polymers",
    "Biomolecules",
    "CIEL"


]